---
title: "Distribution check"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)

data <- read.table(file =here("output.txt"), header = FALSE, as.is = FALSE)
data <- as.numeric(as.character(unlist(data)))

summary(data)
print(paste('Std:' , round(sd(data),3)))


# Kolmogorov-Smirnov Test
ks.test(data, "pnorm", mean=mean(data), sd=sd(data))

# Chi-square test
bin_width <- 2 * IQR(data) * length(data)^(-1/3)
num_bins <- diff(range(data)) / bin_width
num_bins <- ceiling(num_bins)

# Create breaks for binning
breaks <- seq(min(data), max(data), length.out = num_bins)
# Bin the data
binned_data <- cut(data, breaks = breaks, include.lowest = TRUE)
# Count frequencies
freq <- table(binned_data)
# Calculate expected frequencies assuming normal distribution
exp_freq <- diff(pnorm(breaks, mean = 2, sd = 0.3)) * length(data)
# Perform chi-square test
chisq.test(freq, p = exp_freq , rescale.p = TRUE)

# Visual Inspection
hist(data, prob=TRUE, col="lightblue", main="Histogram with Density Curve")
lines(density(data), col="red")
curve(dnorm(x, mean=mean(data), sd=sd(data)), add=TRUE, col="black")

# Q-Q Plot
qqnorm(data)
qqline(data, col = "red")


```
```{r}
exp_data<- read.table(file =here("outputE.txt"), header = FALSE, as.is = FALSE)
exp_data <- as.numeric(as.character(unlist(exp_data)))

lambda <- 1.5
n <- 5000

# Summary statistics
summary(exp_data)

# Histogram
hist(exp_data, breaks = 30, freq = FALSE, col = "lightblue", main = "Histogram of Exponential Data")

# Compare histogram to the density curve
curve(dexp(x, rate = lambda), col = "red", lwd = 2, add = TRUE)

# Q-Q plot
qqplot(exp_data, qexp(ppoints(n), rate = lambda), main = "Q-Q Plot of Exponential Data")
abline(0, 1, col = "red", lwd = 2)


# Kolmogorov-Smirnov test for exponentiality
ks.test(exp_data, "pexp", rate = lambda)
```
